# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ab4f38359b8ab60af9b98e7e94d14b41ea9a0ac5cdc2ed46bbcc6d12892eeb6f9536cfafdce941d8696e080247a5b8dd51f33e598bd0935786a6403470b49da

test:
  secret_key_base: 560f1e1c2eaf60f310195340ce94c0be2a4f401ee5f3c420ddd7ee4ab909b1529c68d58b98b3723f16b421d00725195fd9f867e343d5f8fd190f964ca22bfb04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
